# Generated by Django 3.2.7 on 2021-09-12 19:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cnpj_document', models.CharField(max_length=20)),
                ('rg_document', models.CharField(blank=True, max_length=20, null=True)),
                ('ie_number', models.CharField(blank=True, max_length=20, null=True)),
                ('im_document', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(max_length=400)),
                ('main_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
            ],
        ),
    ]
